#NoEnv
#Include <FindText>
#SingleInstance Force
; Generated by Auto-GUI 3.0.1
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

FileInstall, C:\Users\Administrator\Desktop\pic.png, %A_Temp%\pic.png, 1

Gui -SysMenu +AlwaysOnTop
Gui Font, s13 Bold cBlack
Gui Add, Picture, x229 y6 w414 h780, %A_Temp%\pic.png
Gui Font
Gui Font, s13 Bold cBlack
Gui Add, Text, x8 y272 w224 h226, 使用说明：`n`n先打开 安知宝 小程序`n`n进入到右图界面`n`n程序开始后`n不要用鼠标移动 `n安知宝 小程序 
Gui Font
Gui Font, s14 Bold cBlack
Gui Add, Button, x32 y528 w156 h92 gstart, 开始运行
Gui Font

Gui Show, w654 h797, 消息
Return

GuiEscape:
GuiClose:
    ExitApp


; 点击按钮跳转到 azb
start:
Goto, azb


azb:

; 关闭 gui 窗口
Gui, Destroy

if A_ScreenDPI != 96
{
	MsgBox,, 通知, 仅支持电脑 DPI(屏幕缩放) 为 100`%`n请修改 DPI(屏幕缩放) 为 100`%
	ExitApp
}

; 置顶 安知宝小程序
WinSet AlwaysOnTop, On, 安知宝 ahk_class Chrome_WidgetWin_0


wdkc:="|<我的课程>*169$56.3f1317y6zb28UU98b88EUTDVTsm2zzoI84WyzV2172tzX00EWF8WG8nz7d7l8UUS4D3V4+/zrF0ElF0W32ny4QIE8fcg41Mhw2B9X11k6FD2W4rzU"
; 等待 10s 我的课程 出现
wdkcOK:=FindText(X:="wait", Y:=10, 0,0,0,0,0,0,wdkc)
if (wdkcOK:=FindText(X, Y, 1534-150000, 275-150000, 1534+150000, 275+150000, 0, 0, wdkc))
{
	FindText().Click(X, Y, "L")
}


loop
{


	ssgs:="|<所属归属>*172$51.337zUU1zvXUU4by81EE7zYUFzu20V0Y28ETE5zYUFTu/wd4Zy+FFG5zY0FTvuE10U20EFW/zZ0Gzu4FFE82IIFW+z3Tmjo8GEQE2Y7U"
	; 等待 10s 所属归属 出现
	ssgsOK:=FindText(X:="wait", Y:=10, 0,0,0,0,0,0,ssgs)
	if (ssgsOK:=FindText(X, Y, 1600-150000, 374-150000, 1600+150000, 374+150000, 0, 0, ssgs))
	{
		; 点击 所属归属
		FindText().Click(X, Y, "L")
	}
	else
	{
		break
	}


	/*
	timeIcon:="|<时间>*204$17.0y07z0Tz3zz7zzTzyzjxzTzyTzwzzzzTzyTzwTzkTz0Tw0DUE"
	; 等待 10s 时间图标 出现
	timeIconOk:=FindText(X:="wait", Y:=10, 0,0,0,0,0,0,timeIcon)
	if (timeIconOk:=FindText(X, Y, 1470-150000, 604-150000, 1470+150000, 604+150000, 0, 0, timeIcon))
	{
		; 点击 时间 图标
		FindText().Click(X, Y, "L")
	}
	else
	{
		break
	}
	*/

	; 将 FindText 绑定至 安知宝小程序
	; FindText().BindWindow(WinExist("安知宝 ahk_class Chrome_WidgetWin_0"))

	zxxx :="|<在线学习>**50$51.102/WMXzsM0V09c01TzdDrzsU8E1TUU33148SA1z049V0Vy0M03/z0w0601v11sZzz1ns885081sN10Mm10M388CTE800FzzAA700yU"
	yxx:="|<已学习>*223$37.zw92DzU22G00k1DzlUS0a08AD0Ezk17zs0M02k40M07M0TzkQg0k81kK0M41U/082004zw700wU"
	; 等待 10s 在线学习出现
	zxxxOk:=FindText(X:="wait", Y:=10, 0,0,0,0,0,0,zxxx)
	if (zxxxOk:=FindText(X, Y, 1800-150000, 668-150000, 1800+150000, 668+150000, 0, 0, zxxx))
	{
		; 点击 在线学习
		FindText().Click(X, Y, "L")
		; 无限等待 已学习 出现
		yxxOk:=FindText(X:="wait", Y:=-1, zxxxOk[1][1],zxxxOk[1][2]-8,zxxxOk[1][1]+53,zxxxOk[1][2]+15,yxx)
		
	}



	zxxx :="|<在线学习>**50$51.102/WMXzsM0V09c01TzdDrzsU8E1TUU33148SA1z049V0Vy0M03/z0w0601v11sZzz1ns885081sN10Mm10M388CTE800FzzAA700yU"
	yxx:="|<已学习>*223$37.zw92DzU22G00k1DzlUS0a08AD0Ezk17zs0M02k40M07M0TzkQg0k81kK0M41U/082004zw700wU"
	if (zxxxOk:=FindText(X, Y, 1800-150000, 668-150000, 1800+150000, 668+150000, 0, 0, zxxx))
	{
		; 遍历 "ok" 中的所有搜索结果. "k" 表示第几个结果，"v" 表示结果本身
		for k, v in zxxxOk
		{
			; MsgBox, % "找到第" k "个`nvx=" v[1] "`nvy=" v[2]"`nkx=" zxxxOk[k].x "`nky=" zxxxOk[k].y
			; ToolTip, % "找到第" k "个在线学习`nx=" v[1] "`ny=" v[2]
			; FindText().MouseTip(zxxxOk[k].x, zxxxOk[k].y)
			
			; 点击 在线学习
			FindText().Click(zxxxOk[k].x, zxxxOk[k].y, "L")
			Sleep, 1000
			
			
			; ok:=FindText(X:="wait", Y:=3, 0,0,0,0,0,0,Text)    ; 等待3秒等图像出现
			; 无限等待 在线学习 消失
			; zxxxOk:=FindText(X:="wait0", Y:=-1, v[1],v[2]-10,v[1]+53,v[2]+20,0,0,zxxx)
			
			ToolTip, 无限等待 已学习 出现
			; 无限等待 已学习 出现
			yxxOk:=FindText(X:="wait", Y:=-1, v[1],v[2]-10,v[1]+53,v[2]+20,0,0,yxx)
			ToolTip
			
		}
		
	}


	if (yxxOk:=FindText(X, Y, 1800-150000, 668-150000, 1800+150000, 668+150000, 0, 0, yxx))
	{
		FindText().Click(X-50, Y, "L")
		Sleep, 500
		Send, {PgDn}
		Sleep, 500
		wcxx:="|<完成学习>*181$63.zbzzZwnnzzzwzzwXnAQ00U03zbSRjzzZzyM01007zwzzzTbvzwtza01vwzTzblwzzz0aS07zbbzzvYnzlzzZU03QYzwzzljnDvaC007lxytmQnjxzkzjbCEANzjwztltmz1Dxzzz8z0bnVwDzw3U"
		if (wcxxOk:=FindText(X, Y, 1499-150000, 812-150000, 1499+150000, 812+150000, 0, 0, wcxx))
		{
			
			FindText().Click(X, Y, "L")
			Sleep,500
			
			; 把 安知宝 和 FindText 解绑
			; FindText().BindWindow(0)
		}
		
	}

}

	; 取消置顶 安知宝小程序
	WinSet AlwaysOnTop, Off, 安知宝 ahk_class Chrome_WidgetWin_0


ExitApp
